version: "3.8"
services:

  db:
    image: postgres:15.1-alpine
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: mentorship
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432"

  server:
    image: shecodesvietnam/pifnetwork:2.0.0-rc.2
    container_name: s-master
    env_file: .env
    environment:
      NODE_ENV: production 
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  pgdata:
